
runnames = c("\n3D chromatogram \n generated by first run", 
             "\n3D chromatogram \n generated by second run",
             "\n3D chromatogram \n generated by third run")
ratios = c(1,2,3)
pdf('../imgbin/PeakArea.pdf', width=7, height=3.3)
par(mar = c(1/4, 1/4, 1.5+1/4, 1/4), oma = c(0, 0, 0, 0), mgp=c(2.2,1,0))
layout(matrix(c(1,2,3,4,5,5,5,5), 2, 4, byrow = TRUE), heights=c(3,1.2), widths=c(1,1,1,0.3))

for(plotindex in 1:3) {
  plot(1, xlim = c(-0.4, 1), ylim = c(-0.05, 1.1), type='n', axes=F, xlab="", ylab="", xaxt='n', yaxt='n', bty="n")
  title(runnames[plotindex], cex.main=1)
  
  polygon(c(0, -0.35, 0.55, 0.9), c(0, 0.7, 0.7, 0), border=NA, col = "#DDDDDD")
  
  RT = seq(0,1,0.01) 
  
  RT1  = RT - 0.1 
  TIC1 = rnorm(1,1,0.11)*0.30*exp(-5^2*((RT1+0.1)-0.5)^2*1.5) + 0.2
  RT2  = RT - 0.3
  TIC2 = rnorm(1,1,0.10)*0.45*exp(-5^2*((RT2+0.3)-0.5)^2*1.5) + 0.6
  
  for(i in 2:99) {rect(RT2[i-1], 0.6, RT2[i], TIC2[i], col="#FF8888", border=NA)}
  text(0.5-0.3-0.01/3, 0.6+0.12, "PeakArea", cex=0.88)
  text(0.5-0.3-0.01/3, 0.6+0.1/2, "X")
  for(i in 2:99) {rect(RT1[i-1], 0.2, RT1[i], TIC1[i], col="#8888FF", border=NA)}
  text(0.5-0.1-0.01/3, 0.2+0.12, "PeakArea", cex=0.88)
  text(0.5-0.1-0.01/3, 0.2+0.1/2, "Y")
  
  Y = sum(TIC1-0.2); X = sum(TIC2-0.6)
  ratios[plotindex] = round((X/(X+Y)), digits=3)
  text(0.7, 0.9, bquote(over(X, X+Y) %~~% .(ratios[plotindex])))
  
  arrows(0, 0,  1, 0, length=0.1)
  arrows(0, 0,  0, 1, length=0.1)
  arrows(0, 0, -0.4, 0.8, length=0.1)
  text( 0.5,     -0.05,     "Retention time (RT)",    srt=0,         cex=0.99)
  text(-0.05,     0.5,      "Absolute intensity",     srt=90,        cex=0.99)
  text(-0.2-0.04, 0.4-0.04, "m/z", srt=80+asin(1/2)*(360/2/pi), cex=0.99)
}

plot(1, xlim = c(-1, 1), ylim = c(-1, 1), type='n', axes=F, xlab="", ylab="", xaxt='n', yaxt='n', bty="n",main=NA)
text(0, 0, "etc.\n. . .", cex=2)

plot(1, xlim = c(-1, 1), ylim = c(-1, 1), type='n', axes=F, xlab="", ylab="", xaxt='n', yaxt='n', bty="n",main=NA)
text(0, 0.8, "All runs are repeated (i.e. same sample, same instrument, and same configuration for such instrument).", cex=1.25)
text(0, 0.0, expression(paste("Variability of ", over(X, X+Y), "  can be experimentally characterized by multiple repeated runs.")), cex=1.25)
text(0,-0.8, "Our objective is to use only one run to characterize such variability that exists among repeated runs.", cex=1.25)

dev.off()